import {
  Code,
  Smartphone,
  Globe,
  Layers,
  Palette,
  Server,
  Cloud,
  FileCode,
  ClipboardCheck,
  BarChart3,
  Cpu,
  Briefcase,
  ShoppingCart,
  LineChart,
  Database,
  Brain,
  MessageSquare,
  Glasses,
  Wifi,
  Bitcoin,
  BarChart,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

export interface Service {
  title: string
  slug: string
  icon: LucideIcon
  shortDescription: string
  fullDescription: string
  features: string[]
  benefits: string[]
}

export const services: Service[] = [
  {
    title: "Mobile App Development",
    slug: "mobile-app-development",
    icon: Smartphone,
    shortDescription: "Create powerful, user-friendly mobile applications for iOS and Android platforms.",
    fullDescription:
      "Our mobile app development services deliver cutting-edge applications that engage users and drive business growth. We specialize in creating native and cross-platform apps that provide seamless experiences across iOS and Android devices.",
    features: [
      "Native iOS and Android development",
      "Cross-platform development with React Native and Flutter",
      "UI/UX design for mobile applications",
      "App store optimization and deployment",
      "Maintenance and support services",
      "Integration with backend systems and APIs",
    ],
    benefits: [
      "Expand your reach to mobile users",
      "Increase customer engagement and loyalty",
      "Create new revenue streams",
      "Improve operational efficiency",
      "Enhance brand visibility and recognition",
    ],
  },
  {
    title: "Web Development",
    slug: "web-development",
    icon: Globe,
    shortDescription: "Build responsive, high-performance websites and web applications.",
    fullDescription:
      "Our web development services focus on creating modern, responsive websites and web applications that deliver exceptional user experiences. We leverage the latest technologies and best practices to build solutions that are fast, secure, and scalable.",
    features: [
      "Responsive website design and development",
      "Progressive Web Applications (PWAs)",
      "Single Page Applications (SPAs)",
      "Content Management Systems (CMS)",
      "E-commerce platforms",
      "Performance optimization and SEO",
    ],
    benefits: [
      "Establish a strong online presence",
      "Improve user engagement and conversion rates",
      "Enhance accessibility across devices",
      "Optimize for search engines",
      "Scale your digital capabilities",
    ],
  },
  {
    title: "Custom Software Development",
    slug: "custom-software-development",
    icon: Code,
    shortDescription: "Develop tailored software solutions to address your unique business challenges.",
    fullDescription:
      "Our custom software development services provide bespoke solutions designed specifically for your business needs. We follow a collaborative approach to understand your requirements and deliver software that streamlines operations and drives growth.",
    features: [
      "Requirements analysis and planning",
      "Architecture design and development",
      "Quality assurance and testing",
      "Deployment and integration",
      "Documentation and knowledge transfer",
      "Ongoing maintenance and support",
    ],
    benefits: [
      "Streamline business processes",
      "Increase operational efficiency",
      "Reduce costs and eliminate redundancies",
      "Gain competitive advantage",
      "Scale your business operations",
    ],
  },
  {
    title: "IT Consultation and Planning",
    slug: "it-consultation-planning",
    icon: FileCode,
    shortDescription: "Get expert guidance on technology strategy and implementation.",
    fullDescription:
      "Our IT consultation and planning services provide expert guidance on technology strategy and implementation. We help businesses align their IT initiatives with their business goals, identify opportunities for innovation, and develop roadmaps for digital transformation.",
    features: [
      "Technology assessment and gap analysis",
      "IT strategy development",
      "Digital transformation roadmapping",
      "Vendor selection and management",
      "Technology risk assessment",
      "IT governance and compliance",
    ],
    benefits: [
      "Align IT initiatives with business goals",
      "Optimize technology investments",
      "Reduce technology risks",
      "Accelerate digital transformation",
      "Improve decision-making with expert insights",
    ],
  },
  {
    title: "MVP Development",
    slug: "mvp-development",
    icon: Layers,
    shortDescription: "Quickly validate your business idea with a Minimum Viable Product.",
    fullDescription:
      "Our MVP development services help startups and enterprises validate their ideas quickly and cost-effectively. We focus on building the core features that demonstrate your product's value proposition, allowing you to gather user feedback and iterate rapidly.",
    features: [
      "Idea validation and concept refinement",
      "Core feature development",
      "Rapid prototyping and iteration",
      "User testing and feedback collection",
      "Analytics integration for performance tracking",
      "Scalable architecture for future growth",
    ],
    benefits: [
      "Validate your business idea with minimal investment",
      "Get to market faster",
      "Gather valuable user feedback early",
      "Attract investors with a working product",
      "Reduce development risks",
    ],
  },
  {
    title: "UI/UX Development",
    slug: "ui-ux-development",
    icon: Palette,
    shortDescription: "Create intuitive, engaging user interfaces and experiences.",
    fullDescription:
      "Our UI/UX development services focus on creating intuitive, engaging user interfaces and experiences that delight your users. We combine design thinking, user research, and technical expertise to build interfaces that are both beautiful and functional.",
    features: [
      "User research and persona development",
      "Information architecture and wireframing",
      "Interactive prototyping",
      "Visual design and branding",
      "Usability testing and iteration",
      "Responsive and accessible design",
    ],
    benefits: [
      "Improve user satisfaction and retention",
      "Increase conversion rates and engagement",
      "Reduce support costs through intuitive design",
      "Differentiate your product from competitors",
      "Build brand loyalty through consistent experiences",
    ],
  },
  {
    title: "DevOps",
    slug: "devops",
    icon: Server,
    shortDescription: "Streamline your development and operations processes.",
    fullDescription:
      "Our DevOps services help organizations streamline their development and operations processes, enabling faster delivery of high-quality software. We implement automation, continuous integration/continuous deployment (CI/CD), and infrastructure as code to improve efficiency and reliability.",
    features: [
      "CI/CD pipeline implementation",
      "Infrastructure as Code (IaC)",
      "Containerization and orchestration",
      "Monitoring and logging",
      "Security automation",
      "Performance optimization",
    ],
    benefits: [
      "Accelerate software delivery",
      "Improve code quality and reliability",
      "Reduce deployment failures and rollbacks",
      "Enhance collaboration between development and operations",
      "Increase operational efficiency",
    ],
  },
  {
    title: "SaaS Development",
    slug: "saas-development",
    icon: Cloud,
    shortDescription: "Build scalable, multi-tenant Software-as-a-Service applications.",
    fullDescription:
      "Our SaaS development services help businesses create scalable, multi-tenant software applications delivered over the cloud. We focus on building solutions that are secure, scalable, and provide excellent user experiences while generating recurring revenue.",
    features: [
      "Multi-tenant architecture design",
      "Subscription and billing management",
      "User management and authentication",
      "Data security and privacy",
      "API development and integration",
      "Analytics and reporting",
    ],
    benefits: [
      "Create recurring revenue streams",
      "Scale your business efficiently",
      "Reduce customer acquisition costs",
      "Improve customer lifetime value",
      "Gather valuable usage data and insights",
    ],
  },

  {
    title: "Quality Assurance & Testing",
    slug: "quality-assurance-testing",
    icon: ClipboardCheck,
    shortDescription: "Ensure your software meets the highest quality standards.",
    fullDescription:
      "Our quality assurance and testing services ensure that your software meets the highest quality standards. We implement comprehensive testing strategies to identify and resolve issues early in the development cycle, reducing costs and improving user satisfaction.",
    features: [
      "Test strategy and planning",
      "Manual and automated testing",
      "Performance and load testing",
      "Security testing",
      "Usability and accessibility testing",
      "Continuous integration testing",
    ],
    benefits: [
      "Improve software quality and reliability",
      "Reduce development costs by catching issues early",
      "Enhance user satisfaction and retention",
      "Minimize post-release issues and support costs",
      "Meet compliance and regulatory requirements",
    ],
  },
  {
    title: "Digital Transformation",
    slug: "digital-transformation",
    icon: BarChart3,
    shortDescription: "Modernize your business with digital technologies and processes.",
    fullDescription:
      "Our digital transformation services help businesses modernize their operations with digital technologies and processes. We work with you to identify opportunities for innovation, implement new technologies, and develop the capabilities needed to thrive in the digital age.",
    features: [
      "Digital maturity assessment",
      "Technology roadmap development",
      "Process digitization and automation",
      "Data strategy and analytics",
      "Change management and training",
      "Digital culture development",
    ],
    benefits: [
      "Improve operational efficiency",
      "Enhance customer experiences",
      "Create new business models and revenue streams",
      "Increase agility and responsiveness",
      "Gain competitive advantage",
    ],
  },
  {
    title: "Digital Product Engineering",
    slug: "digital-product-engineering",
    icon: Cpu,
    shortDescription: "Design, develop, and scale innovative digital products.",
    fullDescription:
      "Our digital product engineering services help businesses design, develop, and scale innovative digital products. We combine product thinking, engineering excellence, and user-centered design to create products that solve real problems and deliver value to users.",
    features: [
      "Product strategy and roadmapping",
      "User research and experience design",
      "Agile development and delivery",
      "Quality engineering and DevOps",
      "Product analytics and optimization",
      "Continuous innovation and improvement",
    ],
    benefits: [
      "Accelerate time-to-market",
      "Reduce development risks",
      "Create products that users love",
      "Scale efficiently as your user base grows",
      "Continuously improve based on user feedback",
    ],
  },
  {
    title: "Enterprise Mobility",
    slug: "enterprise-mobility",
    icon: Briefcase,
    shortDescription: "Enable your workforce with secure, efficient mobile solutions.",
    fullDescription:
      "Our enterprise mobility services help businesses enable their workforce with secure, efficient mobile solutions. We develop mobile strategies, implement mobile device management, and create custom mobile applications that improve productivity and collaboration.",
    features: [
      "Mobile strategy development",
      "Enterprise mobile app development",
      "Mobile device management (MDM)",
      "Mobile security and compliance",
      "BYOD policy development",
      "Mobile workflow optimization",
    ],
    benefits: [
      "Improve workforce productivity",
      "Enable remote and field work",
      "Enhance collaboration and communication",
      "Secure sensitive corporate data",
      "Reduce operational costs",
    ],
  },
  {
    title: "eCommerce Development",
    slug: "ecommerce-development",
    icon: ShoppingCart,
    shortDescription: "Build powerful online stores and marketplaces.",
    fullDescription:
      "Our eCommerce development services help businesses build powerful online stores and marketplaces. We create custom eCommerce solutions or implement leading platforms like Shopify, WooCommerce, and Magento to help you sell products and services online.",
    features: [
      "Custom eCommerce development",
      "Platform implementation (Shopify, WooCommerce, Magento)",
      "Payment gateway integration",
      "Inventory and order management",
      "Mobile commerce optimization",
      "Personalization and recommendation engines",
    ],
    benefits: [
      "Expand your market reach",
      "Increase sales and revenue",
      "Improve customer shopping experiences",
      "Gain valuable customer insights",
      "Operate your business 24/7",
    ],
  },
  {
    title: "Digital Marketing",
    slug: "digital-marketing",
    icon: LineChart,
    shortDescription: "Grow your online presence and attract more customers.",
    fullDescription:
      "Our digital marketing services help businesses grow their online presence and attract more customers. We develop comprehensive digital marketing strategies that leverage SEO, content marketing, social media, and paid advertising to drive traffic, leads, and sales.",
    features: [
      "Digital marketing strategy",
      "Search engine optimization (SEO)",
      "Content marketing",
      "Social media marketing",
      "Pay-per-click (PPC) advertising",
      "Email marketing and automation",
    ],
    benefits: [
      "Increase website traffic and visibility",
      "Generate more leads and sales",
      "Build brand awareness and authority",
      "Improve customer engagement and loyalty",
      "Measure and optimize marketing ROI",
    ],
  },
  {
    title: "Cloud",
    slug: "cloud",
    icon: Database,
    shortDescription: "Leverage cloud technologies for scalability, security, and cost efficiency.",
    fullDescription:
      "Our cloud services help businesses leverage cloud technologies for scalability, security, and cost efficiency. We provide cloud strategy, migration, and management services that enable you to take full advantage of cloud platforms like AWS, Azure, and Google Cloud.",
    features: [
      "Cloud strategy and architecture",
      "Cloud migration and modernization",
      "Infrastructure as a Service (IaaS)",
      "Platform as a Service (PaaS)",
      "Serverless architecture",
      "Cloud security and compliance",
    ],
    benefits: [
      "Reduce IT infrastructure costs",
      "Scale resources up or down as needed",
      "Improve business continuity and disaster recovery",
      "Accelerate innovation and time-to-market",
      "Enhance security and compliance",
    ],
  },
  {
    title: "Artificial Intelligence and Machine Learning",
    slug: "ai-ml",
    icon: Brain,
    shortDescription: "Harness the power of AI and ML to gain insights and automate processes.",
    fullDescription:
      "Our AI and ML services help businesses harness the power of artificial intelligence and machine learning to gain insights and automate processes. We develop custom AI solutions that analyze data, make predictions, and optimize operations to drive business value.",
    features: [
      "AI strategy and use case identification",
      "Machine learning model development",
      "Natural language processing",
      "Computer vision",
      "Predictive analytics",
      "AI-powered automation",
    ],
    benefits: [
      "Gain actionable insights from your data",
      "Automate repetitive tasks and processes",
      "Improve decision-making with predictive analytics",
      "Enhance customer experiences with personalization",
      "Identify new opportunities and optimize operations",
    ],
  },
  {
    title: "Chatbot Development",
    slug: "chatbot-development",
    icon: MessageSquare,
    shortDescription: "Create intelligent conversational interfaces for customer service and support.",
    fullDescription:
      "Our chatbot development services help businesses create intelligent conversational interfaces for customer service and support. We build chatbots and virtual assistants that can understand natural language, answer questions, and perform tasks to improve customer experiences and reduce support costs.",
    features: [
      "Natural language processing and understanding",
      "Multi-channel deployment (web, mobile, messaging platforms)",
      "Integration with backend systems and APIs",
      "Contextual conversation management",
      "Analytics and performance tracking",
      "Continuous learning and improvement",
    ],
    benefits: [
      "Provide 24/7 customer support",
      "Reduce support costs and wait times",
      "Handle multiple customer inquiries simultaneously",
      "Collect valuable customer data and insights",
      "Free up human agents for complex issues",
    ],
  },
  {
    title: "Augmented Reality",
    slug: "augmented-reality",
    icon: Glasses,
    shortDescription: "Create immersive AR experiences for various applications.",
    fullDescription:
      "Our augmented reality services help businesses create immersive AR experiences for various applications. We develop AR solutions for marketing, training, product visualization, and more, enhancing user engagement and providing innovative ways to interact with your brand.",
    features: [
      "AR app development for iOS and Android",
      "WebAR solutions",
      "3D modeling and animation",
      "AR for product visualization",
      "AR for training and education",
      "Location-based AR experiences",
    ],
    benefits: [
      "Create memorable and engaging user experiences",
      "Showcase products in interactive 3D",
      "Reduce training costs with immersive learning",
      "Differentiate your brand with innovative technology",
      "Increase user engagement and conversion rates",
    ],
  },
  {
    title: "Internet of Things",
    slug: "internet-of-things",
    icon: Wifi,
    shortDescription: "Connect devices and systems to create smart, data-driven solutions.",
    fullDescription:
      "Our IoT services help businesses connect devices and systems to create smart, data-driven solutions. We develop IoT strategies, implement connected device ecosystems, and build platforms that collect and analyze data from sensors and devices to drive operational improvements.",
    features: [
      "IoT strategy and architecture",
      "Connected device development",
      "IoT platform implementation",
      "Edge computing solutions",
      "IoT data analytics",
      "IoT security and privacy",
    ],
    benefits: [
      "Improve operational efficiency with real-time data",
      "Enable predictive maintenance to reduce downtime",
      "Create new revenue streams with connected products",
      "Enhance decision-making with IoT analytics",
      "Improve customer experiences with smart products",
    ],
  },
  {
    title: "Blockchain",
    slug: "blockchain",
    icon: Bitcoin,
    shortDescription: "Implement secure, transparent blockchain solutions for your business.",
    fullDescription:
      "Our blockchain services help businesses implement secure, transparent blockchain solutions. We develop blockchain strategies, smart contracts, decentralized applications, and enterprise blockchain solutions that enhance security, transparency, and efficiency.",
    features: [
      "Blockchain strategy and consulting",
      "Smart contract development",
      "Decentralized application (DApp) development",
      "Enterprise blockchain solutions",
      "Cryptocurrency and token development",
      "Blockchain security audits",
    ],
    benefits: [
      "Enhance security and reduce fraud",
      "Increase transparency and trust",
      "Streamline processes with smart contracts",
      "Reduce costs by eliminating intermediaries",
      "Create new business models with tokenization",
    ],
  },
  {
    title: "Big Data",
    slug: "big-data",
    icon: BarChart,
    shortDescription: "Harness the power of big data to gain insights and drive decisions.",
    fullDescription:
      "Our big data services help businesses harness the power of big data to gain insights and drive decisions. We implement big data architectures, develop data pipelines, and create analytics solutions that transform raw data into actionable intelligence.",
    features: [
      "Big data strategy and architecture",
      "Data lake and warehouse implementation",
      "ETL and data pipeline development",
      "Real-time data processing",
      "Data visualization and dashboards",
      "Predictive analytics and machine learning",
    ],
    benefits: [
      "Make data-driven decisions with confidence",
      "Identify patterns and trends in large datasets",
      "Improve forecasting and planning",
      "Enhance customer understanding and segmentation",
      "Optimize operations with data-driven insights",
    ],
  },
]

